author:
  name: Tony Truong
  email: dacton.truong@gmail.com
  title: Gamer & Plumber
  github: https://github.com/sicay1
  description: Code - Play - Fix - Learn - Share
description: >-  
  A simple Jekyll blog scaffolded for local development.
footer_text: "2025 Tony Truong - ❤️ Jekyll."
# baseurl: "/blog"
url: "https://sicay1.github.io/blog"

# Build settings
theme: minima
plugins:
  - jekyll-feed
